name: hellohand_mobile
description: HelloHand - Traductor de Lenguaje de Se침as en Tiempo Real (Mobile)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Material Design
  cupertino_icons: ^1.0.8
  
  # HTTP y Networking
  http: ^1.1.0
  dio: ^5.3.2
  
  # WebSocket
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Audio y C치mara
  permission_handler: ^11.0.1
  camera: ^0.10.5+5
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3
  audioplayers: ^5.2.1
  
  # Utilidades
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.1
  
  # Estado y navegaci칩n
  provider: ^6.1.1
  go_router: ^12.1.1
  
  # JSON y serializaci칩n
  json_annotation: ^4.8.1
  
  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
